//
// Created by David Halonen on 2/15/21.
//

#ifndef RASPBERRYPITEMPSENSOR_COOLINGFILTERTEST_H
#define RASPBERRYPITEMPSENSOR_COOLINGFILTERTEST_H


class CoolingFilterTest {

};


#endif //RASPBERRYPITEMPSENSOR_COOLINGFILTERTEST_H
